name: 'Lock down repository'

on:
  issues:
    types: opened
  pull_request:
    types: opened
  schedule:
    - cron: '0 * * * *'

jobs:
  lockdown:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v2
        with:
          github-token: ${{ github.token }}
          exclude-issue-created-before: ''
          exclude-issue-labels: ''
          issue-labels: ''
          issue-comment: 'Please reopen this issue at https://github.com/lucasvog/dvbfast/issues . This repo is only for hosting the website and because of that, this issue would not be seen. Thanks! ****  Bitte dieses Problem unter den genannten Link angeben, nicht hier. In diesem Repo liegt nur die Webseite, und das Problem würde sonst nicht gesehen werden. Danke!'
          skip-closed-issue-comment: false
          close-issue: true
          lock-issue: true
          issue-lock-reason: ''
          exclude-pr-created-before: ''
          exclude-pr-labels: ''
          pr-labels: ''
          pr-comment: ''
          skip-closed-pr-comment: false
          close-pr: true
          lock-pr: true
          pr-lock-reason: ''
          process-only: ''
